export const START_CHECKIN_REQUEST = 'START_CHECKIN_REQUEST';
export const CHECKIN_SUCCESS = 'CHECKIN_SUCCESS';
export const CHECKIN_FAIL = 'CHECKIN_FAIL';

export const START_CHECKOUT_REQUEST = 'START_CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAIL = 'CHECKOUT_FAIL';

export const START_TAKEBREAK_REQUEST = 'START_TAKEBREAK_REQUEST';
export const TAKEBREAK_SUCCESS = 'TAKEBREAK_SUCCESS';
export const TAKEBREAK_FAIL = 'TAKEBREAK_FAIL';

export const START_STOPBREAK_REQUEST = 'START_STOPBREAK_REQUEST';
export const STOPBREAK_SUCCESS = 'STOPBREAK_SUCCESS';
export const STOPBREAK_FAIL = 'STOPBREAK_FAIL';
