export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAIL = 'POST_LOGIN_FAIL';

export const SAVE_REMEMBERME = 'SAVE_REMEMBERME';
export const SAVE_REMEMBERME_FAIL = 'SAVE_REMEMBERME_FAIL';

// export const SAVE_REMEMBERME = 'SAVE_REMEMBERME';
// export const SAVE_REMEMBERME_FAIL = 'SAVE_REMEMBERME_FAIL';

// export const FORGET_PASSWORD = "FORGET_PASSWORD"
// export const FORGET_PASSWORD = "FORGET_PASSWORD"
// export const RESET_PASSWORD = "RESET_PASSWORD"
// export const RESET_PASSWORD = "RESET_PASSWORD"
