export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_POST_SUCCESS = 'OTP_POST_SUCCESS';
export const OTP_POST_FAIL = 'OTP_POST_FAIL';

export const GET_OTP_TOKEN_SUCCESS = 'GET_OTP_TOKEN_SUCCESS';
export const GET_OTP_TOKEN_FAIL = 'GET_OTP_TOKEN_FAIL';
