export const FETCH_ATTENDANCEBYID_REQUEST = 'FETCH_ATTENDANCEBYID_REQUEST';
export const REQUEST_ATTENDANCEBYID_SUCCESS = 'REQUEST_ATTENDANCEBYID_SUCCESS';
export const REQUEST_ATTENDANCEBYID_FAIL = 'REQUEST_ATTENDANCEBYID_FAIL';
