export const FETCH_USER_DETAIL_REQUEST = 'FETCH_USER_DETAIL_REQUEST';
export const REQUEST_USERDETAIL_SUCCESS = 'REQUEST_USERDETAIL_SUCCESS';
export const REQUEST_USERDETAIL_FAIL = 'REQUEST_USERDETAIL_FAIL';
